_target_: stable_baselines3.ppo.PPO
policy: "MlpPolicy"
verbose: 1
learning_rate: 0.0016069705447393067
n_steps: 1024
batch_size: 8
n_epochs: 10
gamma: 0.999
gae_lambda: 0.95
clip_range: 0.3
ent_coef: 6.674409990826704e-07
max_grad_norm: 0.8
vf_coef: 0.8640380074610406
policy_kwargs: "dict(activation_fn=nn.ReLU)"
